export interface RetryPolicy{maxAttempts:number;baseDelayMs:number;maxDelayMs:number;jitter:number}
export const DEFAULT_RETRY_POLICY:RetryPolicy={maxAttempts:5,baseDelayMs:500,maxDelayMs:30000,jitter:.2}
export function backoffDelay(attempt:number,policy=DEFAULT_RETRY_POLICY,random=Math.random){const exponent=Math.max(0,attempt-1);const raw=Math.min(policy.maxDelayMs,policy.baseDelayMs*2**exponent);const delta=raw*policy.jitter;return Math.max(0,Math.round(raw+(random()*2-1)*delta))}
export async function withRetry<T>(work:(attempt:number)=>Promise<T>,policy=DEFAULT_RETRY_POLICY){let lastError:unknown;for(let attempt=1;attempt<=policy.maxAttempts;attempt++){try{return await work(attempt)}catch(error){lastError=error;if(attempt>=policy.maxAttempts)break;await new Promise(resolve=>setTimeout(resolve,backoffDelay(attempt+1,policy)))}}throw lastError instanceof Error?lastError:new Error('Retry policy exhausted')}
export interface CacheRecord{key:string;sizeBytes:number;lastAccessedAt:number;pinned?:boolean}
export class CachePolicy{constructor(private readonly maxBytes:number){}chooseEvictions(records:CacheRecord[],incomingBytes:number){let total=records.reduce((sum,record)=>sum+record.sizeBytes,0)+incomingBytes;if(total<=this.maxBytes)return[];return[...records].filter(record=>!record.pinned).sort((a,b)=>a.lastAccessedAt-b.lastAccessedAt).filter(record=>{if(total<=this.maxBytes)return false;total-=record.sizeBytes;return true})}}
export interface Quota{maxBytes:number;usedBytes:number}
export class QuotaManager{constructor(private quota:Quota){}canAllocate(bytes:number){return this.quota.usedBytes+bytes<=this.quota.maxBytes}allocate(bytes:number){if(!this.canAllocate(bytes))return false;this.quota.usedBytes+=bytes;return true}release(bytes:number){this.quota.usedBytes=Math.max(0,this.quota.usedBytes-Math.max(0,bytes))}snapshot(){return{...this.quota}}}
export function dedupeByChecksum<T extends {checksum?:string;id:string}>(items:T[]){const seen=new Set<string>();return items.filter(item=>{if(!item.checksum)return true;if(seen.has(item.checksum))return false;seen.add(item.checksum);return true})}
export async function sha256Hex(input:string){const data=new TextEncoder().encode(input);const digest=await crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(digest)).map(byte=>byte.toString(16).padStart(2,'0')).join('')}
export function stableJson(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableJson).join(',')}]`;const record=value as Record<string,unknown>;return`{${Object.keys(record).sort().map(key=>`${JSON.stringify(key)}:${stableJson(record[key])}`).join(',')}}`}
export interface OutboxItem<T>{id:string;operation:'upsert'|'delete';payload:T;createdAt:number}
export class Outbox<T>{private items:OutboxItem<T>[]=[];push(item:Omit<OutboxItem<T>,'createdAt'>){this.items.push({...item,createdAt:Date.now()})}drain(limit=20){return this.items.splice(0,limit)}size(){return this.items.length}restore(items:OutboxItem<T>[]){this.items=[...items,...this.items]}}
