import { ReactNode,useEffect,useMemo,useRef,useState } from 'react'
import { ActivityIndicator,AppState,AppStateStatus,Platform,StyleSheet,Text,View } from 'react-native'
import { Button } from 'react-native-paper'
import { authenticateForSensitiveAction } from '@/src/core/security/BiometricService'
import { enableLock,initialLockModel,isExpired,lock,unlock as unlockModel } from '@/src/core/security/AppLock'
import { loadAppLock,saveAppLock } from '@/src/core/security/appLockPersistence'
import { loadPersistentFlags } from '@/src/core/flags/persistentFlags'
import { onLockRequested } from '@/src/core/security/appLockCoordinator'
import { safeErrorMessage } from '@/src/core/errors/errorMessage'
import { useAppLocale } from '@/src/core/i18n/AppLocaleProvider'
import { lockCopy } from '@/src/core/i18n/localePreference'

export function AppLockGate({children}:{children:ReactNode}){const {locale}=useAppLocale();const copy=useMemo(()=>lockCopy(locale),[locale]);const [status,setStatus]=useState<'loading'|'unlocked'|'locked'>('loading');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const modelRef=useRef(initialLockModel);const unlock=async()=>{if(busy)return;setBusy(true);setMessage('');try{const current=await loadAppLock();const locked=enableLock(current);modelRef.current=locked;await saveAppLock(locked);const result=await authenticateForSensitiveAction(locked.fallbackPolicy);if(result.success){const next=unlockModel(locked);modelRef.current=next;await saveAppLock(next);setStatus('unlocked');setMessage(result.fallback?copy.fallback:'')}else{modelRef.current=lock(locked);await saveAppLock(modelRef.current);setStatus('locked');setMessage(copy.authIncomplete)}}catch(error){modelRef.current=lock(modelRef.current);setStatus('locked');setMessage(copy.unlockFailed(safeErrorMessage(error,'Please try again.')))}finally{setBusy(false)}};
// The lock callback is intentionally owned by this lifecycle boundary; listeners are cleaned up on unmount.
// eslint-disable-next-line react-hooks/exhaustive-deps
useEffect(()=>{let active=true;const hydrate=async()=>{try{const flags=await loadPersistentFlags();const stored=await loadAppLock();modelRef.current=stored;if(!active)return;if(!flags.biometricLock||Platform.OS==='web'){await saveAppLock(initialLockModel);if(active)setStatus('unlocked');return}await unlock()}catch(error){if(active){modelRef.current=lock(modelRef.current);setStatus('locked');setMessage(copy.settingsFailed(safeErrorMessage(error,'Unlock is required to continue.')))}}};void hydrate();const persistLockedState=async(nextModel=lock(modelRef.current),fallbackMessage=copy.locked)=>{modelRef.current=nextModel;try{await saveAppLock(nextModel);if(active){setStatus('locked');setMessage(fallbackMessage)}}catch(error){if(active){setStatus('locked');setMessage(copy.saveFailed(safeErrorMessage(error,'Keep the app open and try again.')))}}};const onStateChange=(next:AppStateStatus)=>{if(next==='active'&&isExpired(modelRef.current))void persistLockedState(lock(modelRef.current),copy.expired)};const subscription=AppState.addEventListener('change',onStateChange);const unsubscribeLock=onLockRequested(()=>{void persistLockedState(lock(modelRef.current),copy.manual)});return()=>{active=false;subscription.remove();unsubscribeLock()}},[]);if(status==='unlocked')return <>{children}</>;return <View style={styles.root}>{status==='loading'?<ActivityIndicator size="large" color="#4F46E5"/>:<><Text accessibilityRole="header" style={styles.title}>{copy.title}</Text><Text style={styles.sub}>{message||copy.prompt}</Text><Button accessibilityLabel={copy.unlock} mode="contained" onPress={()=>void unlock()} disabled={busy} loading={busy}>{copy.unlock}</Button></>}</View>}
const styles=StyleSheet.create({root:{flex:1,alignItems:'center',justifyContent:'center',padding:24,backgroundColor:'#F8FAFC'},title:{fontSize:24,fontWeight:'800',color:'#122033',marginBottom:8},sub:{color:'#667085',textAlign:'center',lineHeight:20,marginBottom:20}})
