import { describe,expect,it } from 'vitest';
import { pendingOfferAgeLabelForLocale,PENDING_OFFER_AGE_LABELS_BY_LOCALE } from '../src/monetization/pendingDiagnostics';
import { canResumeCancelledHistoryEntry,canStartCleanup,CLEANUP_UNDO_WINDOW_SECONDS,cleanupExpiryNotice,cleanupExpiryNoticeForLocale,nextUndoSeconds,recoveryWindowCountdownLabel,recoveryWindowCountdownLabelForLocale,RECOVERY_WINDOW_MESSAGE_LABELS_BY_LOCALE,recoveryWindowCountdownPercent,recoveryWindowCountdownTone,recoveryWindowCountdownPresentation,recoveryWindowCountdownAccessibilityLabel,recoveryWindowCountdownStateCue,recoveryWindowCountdownStateCueForLocale,RECOVERY_WINDOW_CUE_LABELS_BY_LOCALE,recoveryWindowMotionStatusLabel,recoveryWindowStatusLabel,recoveryWindowStatusTone,recoveryWindowStatusPresentation,recoveryActionLabel,RECOVERY_ACTION_LABELS_BY_LOCALE,recoveryDialogLabel,recoveryRestoreDialogMessage,RECOVERY_DIALOG_LABELS_BY_LOCALE,cleanupLabel,cleanupDeleteSelectedLabel,cleanupSelectionAccessibilityLabel,CLEANUP_LABELS_BY_LOCALE,cleanupOutcomeLabel,cleanupOutcomeActionLabel,cleanupOutcomeDetailSeparator,CLEANUP_OUTCOME_LABELS_BY_LOCALE,partialCleanupNoticeForLocale,retryCleanupNoticeForLocale,restoreCleanupNoticeForLocale,restoreManyCleanupNoticeForLocale,CLEANUP_NOTICE_LABELS_BY_LOCALE,cleanupExpiryNoticeForLocaleFromRegistry,cleanupErrorNotice,backupDialogLabel,backupNotice,backupErrorNotice,BACKUP_NOTICE_LABELS_BY_LOCALE,monetizationNotice,monetizationPurchaseSuccess,monetizationErrorNotice,MONETIZATION_NOTICE_LABELS_BY_LOCALE,paywallLabel,paywallProStartsAt,paywallProductPrice,paywallCreditsRemaining,paywallPlanLabel,biometricStatusLabel,storageMigrationLabel,securityLabel,securityTimeoutLabel,PAYWALL_LABELS_BY_LOCALE,partialCleanupNotice,recoveryHistoryEmptyStateLabel,recoveryHistoryEmptyStateLabelForLocale,recoveryHistoryFilterLabel,recoveryHistoryStatusLabel,recoveryHistoryStatusLabelForLocale,RECOVERY_HISTORY_LABELS_BY_LOCALE,recentScanAccessibilityLabel,documentUiLabelsForLocale,DOCUMENT_UI_LABELS_BY_LOCALE,expiredRecoveryEventCount,restoreCancellationAnnouncement,restoreCancellationAnnouncementForLocale,restoreCancellationNotice,restoreProgressAnnouncement,restoreProgressAnnouncementForLocale,RECOVERY_ANNOUNCEMENT_LABELS_BY_LOCALE,restoreManyCleanupNotice,restoreProgressLabel,restoreProgressPercent,retryCleanupNotice,shouldRestoreResumeFocus } from '../src/core/storage/cleanupRecovery';

describe('cleanup recovery helpers',()=>{
  it('uses an eight-second undo window and expires at zero',()=>{
    expect(CLEANUP_UNDO_WINDOW_SECONDS).toBe(8);
    expect(nextUndoSeconds(8)).toBe(7);
    expect(nextUndoSeconds(1)).toBe(0);
    expect(nextUndoSeconds(0)).toBe(0);
    expect(recoveryWindowCountdownLabel(8,true)).toBe('8 seconds left to restore removed documents');
    expect(recoveryWindowCountdownLabel(1,true)).toBe('1 second left to restore removed documents');
    expect(recoveryWindowCountdownLabel(0,false)).toBe('Recovery window expired');
    expect(recoveryWindowCountdownLabelForLocale(2,true,'es-MX',RECOVERY_WINDOW_MESSAGE_LABELS_BY_LOCALE)).toBe('Quedan 2 segundos para restaurar los documentos eliminados');
    expect(recoveryWindowCountdownLabelForLocale(1,true,'es',RECOVERY_WINDOW_MESSAGE_LABELS_BY_LOCALE)).toBe('Queda 1 segundo para restaurar los documentos eliminados');
    expect(recoveryWindowCountdownLabelForLocale(0,false,'es',RECOVERY_WINDOW_MESSAGE_LABELS_BY_LOCALE)).toBe('La ventana de restauración expiró');
    expect(recoveryWindowCountdownLabelForLocale(0,false,'fr-FR',RECOVERY_WINDOW_MESSAGE_LABELS_BY_LOCALE)).toBe('Recovery window expired');
    expect(cleanupExpiryNoticeForLocale('es-MX')).toBe('La ventana de restauración expiró. Cleanup is complete.');
    expect(recoveryWindowCountdownPercent(8,8,true)).toBe(100);
    expect(recoveryWindowCountdownPercent(4,8,true)).toBe(50);
    expect(recoveryWindowCountdownPercent(12,8,true)).toBe(100);
    expect(recoveryWindowCountdownPercent(4,0,true)).toBe(0);
    expect(recoveryWindowCountdownPercent(4,8,false)).toBe(0);
    expect(recoveryWindowCountdownTone(8,8,true)).toBe('active');
    expect(recoveryWindowCountdownTone(2,8,true)).toBe('warning');
    expect(recoveryWindowCountdownTone(0,8,true)).toBe('expired');
    expect(recoveryWindowCountdownTone(2,0,true)).toBe('expired');
    expect(recoveryWindowCountdownPresentation(false)).toBe('standard');
    expect(recoveryWindowCountdownPresentation(true)).toBe('static');
    expect(recoveryWindowCountdownAccessibilityLabel('8 seconds left to restore removed documents','active',false)).toBe('8 seconds left to restore removed documents · active');
    expect(recoveryWindowCountdownAccessibilityLabel('2 seconds left to restore removed documents','warning',true)).toBe('2 seconds left to restore removed documents · warning · reduced motion');
    expect(recoveryWindowMotionStatusLabel(true)).toBe('Reduced motion enabled · countdown is static');
    expect(recoveryWindowMotionStatusLabel(false)).toBe('');
    expect(recoveryWindowStatusLabel(true,8)).toBe('Recovery window active · documents can be restored');
    expect(recoveryWindowStatusLabel(false,0)).toBe('Recovery window expired · documents cannot be restored from this action');
    expect(recoveryWindowStatusTone(true,8)).toBe('active');
    expect(recoveryWindowStatusTone(false,0)).toBe('expired');
    expect(recoveryWindowStatusPresentation(false)).toBe('standard');
    expect(recoveryWindowStatusPresentation(true)).toBe('high-contrast');
    expect(recoveryWindowCountdownTone(8,8,true)).toBe('active');
    expect(recoveryWindowCountdownTone(2,8,true)).toBe('warning');
    expect(recoveryWindowCountdownTone(0,8,false)).toBe('expired');
    expect(recoveryWindowCountdownStateCue('active')).toBe('Ready to restore');
    expect(recoveryWindowCountdownStateCue('warning',{active:'Active',warning:'Closing',expired:'Closed'})).toBe('Closing');
    expect(recoveryWindowCountdownStateCueForLocale('active','es-MX',{'es':{active:'Listo',warning:'Cerrando',expired:'Cerrada'}})).toBe('Listo');
    expect(recoveryWindowCountdownStateCueForLocale('active','es-MX',RECOVERY_WINDOW_CUE_LABELS_BY_LOCALE)).toBe('Listo para restaurar');
    expect(recoveryWindowCountdownStateCueForLocale('warning','es',RECOVERY_WINDOW_CUE_LABELS_BY_LOCALE)).toBe('La ventana de restauración se está cerrando');
    expect(recoveryWindowCountdownStateCueForLocale('expired','de-DE',RECOVERY_WINDOW_CUE_LABELS_BY_LOCALE)).toBe('Restore window closed');
    expect(recoveryWindowCountdownStateCueForLocale('expired','fr-FR',{'en':{active:'Ready',warning:'Closing',expired:'Closed'}})).toBe('Restore window closed');
    expect(cleanupExpiryNotice()).toContain('Undo window expired');
    expect(partialCleanupNotice(1,3)).toContain('1 of 3 selected documents were removed');
    expect(retryCleanupNotice('Tax receipt')).toContain('Tax receipt removed successfully');
    expect(restoreManyCleanupNotice(2,2)).toContain('2 removed documents restored');
    expect(restoreManyCleanupNotice(1,2)).toContain('1 of 2 removed documents restored');
    expect(restoreProgressLabel(1,3)).toBe('Restoring documents… 1/3');
    expect(restoreProgressPercent(1,3)).toBe(33);
    expect(restoreProgressPercent(5,3)).toBe(100);
    expect(restoreProgressPercent(-1,3)).toBe(0);
    expect(restoreProgressPercent(0,0)).toBe(0);
    expect(restoreProgressAnnouncement(1,3,'Passport',false)).toBe('Restoring documents… 1/3 · 33% · Passport');
    expect(restoreProgressAnnouncementForLocale(1,3,'Pasaporte',false,'es-MX',RECOVERY_ANNOUNCEMENT_LABELS_BY_LOCALE)).toBe('Restaurando documentos… 1/3 · 33% · Pasaporte');
    expect(restoreProgressAnnouncementForLocale(1,3,null,true,'fr-FR',RECOVERY_ANNOUNCEMENT_LABELS_BY_LOCALE)).toBe('Selected restore · Restoring documents… 1/3 · 33%');
    expect(restoreProgressAnnouncement(1,3,'Passport',true)).toBe('Selected restore · Restoring documents… 1/3 · 33% · Passport');
    expect(shouldRestoreResumeFocus(true,true)).toBe(true);
    expect(shouldRestoreResumeFocus(true,false)).toBe(false);
    expect(shouldRestoreResumeFocus(false,true)).toBe(false);
    expect(recoveryHistoryEmptyStateLabel('all')).toBe('No recovery history yet.');
    expect(recoveryHistoryEmptyStateLabel('failed')).toBe('No failed recovery events match this filter.');
    expect(recoveryHistoryFilterLabel('cancelled','es-MX',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('Cancelados');
    expect(recoveryHistoryEmptyStateLabelForLocale('all','es',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('Aún no hay historial de recuperación.');
    expect(recoveryHistoryEmptyStateLabelForLocale('failed','es',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('No hay eventos de recuperación fallidos que coincidan con este filtro.');
    expect(recoveryHistoryEmptyStateLabelForLocale('failed','fr-FR',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('No failed recovery events match this filter.');
    expect(canResumeCancelledHistoryEntry('cancelled',true,2,true)).toBe(true);
    expect(canResumeCancelledHistoryEntry('cancelled',false,2,true)).toBe(false);
    expect(canResumeCancelledHistoryEntry('completed',true,2,true)).toBe(false);
    expect(canResumeCancelledHistoryEntry('cancelled',true,0,true)).toBe(false);
    expect(canResumeCancelledHistoryEntry('cancelled',true,2,false)).toBe(false);
    expect(recoveryHistoryStatusLabel('cancelled',true,false)).toBe('Cancelled · Expired');
    expect(recoveryHistoryStatusLabel('cancelled',true,true)).toBe('cancelled');
    expect(recoveryHistoryStatusLabel('completed',true,false)).toBe('completed');
    expect(recoveryHistoryStatusLabelForLocale('cancelled',true,false,'es',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('Cancelado · Expirado');
    expect(recoveryHistoryStatusLabelForLocale('completed',false,true,'es-MX',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('completado');
    expect(recoveryHistoryStatusLabelForLocale('failed',false,true,'fr-FR',RECOVERY_HISTORY_LABELS_BY_LOCALE)).toBe('failed');
    expect(recoveryActionLabel('continueRestoring','es-MX',RECOVERY_ACTION_LABELS_BY_LOCALE)).toBe('Continuar restaurando');
    expect(recoveryActionLabel('undoCleanup','es',RECOVERY_ACTION_LABELS_BY_LOCALE)).toBe('Deshacer última limpieza');
    expect(recoveryActionLabel('restore','fr-FR',RECOVERY_ACTION_LABELS_BY_LOCALE)).toBe('Restore');
    expect(recoveryDialogLabel('cancelRestoreTitle','es-MX',RECOVERY_DIALOG_LABELS_BY_LOCALE)).toBe('¿Cancelar la restauración?');
    expect(recoveryDialogLabel('cancelRestoreMessage','es',RECOVERY_DIALOG_LABELS_BY_LOCALE)).toContain('documentos restantes');
    expect(recoveryRestoreDialogMessage(1,'es',RECOVERY_DIALOG_LABELS_BY_LOCALE)).toBe('¿Restaurar 1 documento en tu biblioteca?');
    expect(recoveryRestoreDialogMessage(2,'fr-FR',RECOVERY_DIALOG_LABELS_BY_LOCALE)).toBe('Restore 2 documents to your library?');
    expect(cleanupLabel('selectAll','es-MX',CLEANUP_LABELS_BY_LOCALE)).toBe('Seleccionar todos');
    expect(cleanupDeleteSelectedLabel(2,'es',CLEANUP_LABELS_BY_LOCALE)).toBe('Eliminar 2 seleccionados');
    expect(cleanupSelectionAccessibilityLabel('keep','Factura.pdf','es',CLEANUP_LABELS_BY_LOCALE)).toBe('Conservar Factura.pdf para la limpieza');
    expect(cleanupLabel('noCandidates','fr-FR',CLEANUP_LABELS_BY_LOCALE)).toBe('No cleanup candidates found.');
    expect(cleanupOutcomeLabel('removed','es-MX',CLEANUP_OUTCOME_LABELS_BY_LOCALE)).toBe('Eliminado');
    expect(cleanupOutcomeLabel('failed','es',CLEANUP_OUTCOME_LABELS_BY_LOCALE)).toBe('No se pudo eliminar');
    expect(cleanupOutcomeActionLabel('es',CLEANUP_OUTCOME_LABELS_BY_LOCALE)).toBe('Reintentar');
    expect(cleanupOutcomeDetailSeparator('fr-FR',CLEANUP_OUTCOME_LABELS_BY_LOCALE)).toBe(' · ');
    expect(partialCleanupNoticeForLocale(1,2,'es',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toContain('Se eliminaron 1 de 2');
    expect(retryCleanupNoticeForLocale('Factura.pdf','es-MX',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toContain('se eliminó correctamente');
    expect(restoreCleanupNoticeForLocale('Factura.pdf','es',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('Factura.pdf se restauró en tu biblioteca de documentos.');
    expect(restoreManyCleanupNoticeForLocale(2,2,'fr-FR',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('2 removed documents restored.');
    expect(cleanupExpiryNoticeForLocaleFromRegistry('es',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('La ventana para deshacer expiró. La limpieza se completó.');
    expect(cleanupErrorNotice('retryFailed','Inténtalo de nuevo.','es',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('El reintento falló. Inténtalo de nuevo.');
    expect(cleanupErrorNotice('restoreFailed','Try again.','fr-FR',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('Restore failed. Try again.');
    expect(cleanupErrorNotice('cleanupFailed','No documents were removed.','es-MX',CLEANUP_NOTICE_LABELS_BY_LOCALE)).toBe('No se pudo completar la limpieza. No documents were removed.');
    expect(backupDialogLabel('deleteTitle','es',BACKUP_NOTICE_LABELS_BY_LOCALE)).toBe('¿Eliminar la copia de seguridad local?');
    expect(backupDialogLabel('restore','es-MX',BACKUP_NOTICE_LABELS_BY_LOCALE)).toBe('Restaurar');
    expect(backupNotice('restored','es',BACKUP_NOTICE_LABELS_BY_LOCALE)).toContain('Copia de seguridad local restaurada');
    expect(backupErrorNotice('restoreFailed','Try again.','es',BACKUP_NOTICE_LABELS_BY_LOCALE)).toBe('No se pudo restaurar la copia de seguridad. Try again.');
    expect(backupNotice('deleted','fr-FR',BACKUP_NOTICE_LABELS_BY_LOCALE)).toBe('Local backup deleted. Your current library is unchanged.');
    expect(monetizationNotice('processing','es-MX',MONETIZATION_NOTICE_LABELS_BY_LOCALE)).toBe('Procesando la compra…');
    expect(monetizationPurchaseSuccess(false,'es',MONETIZATION_NOTICE_LABELS_BY_LOCALE)).toBe('Compra completada. Las funciones Pro están activadas.');
    expect(monetizationPurchaseSuccess(true,'es',MONETIZATION_NOTICE_LABELS_BY_LOCALE)).toBe('Esta oferta ya está activa.');
    expect(monetizationErrorNotice('restoreFailed','Try again.','es',MONETIZATION_NOTICE_LABELS_BY_LOCALE)).toBe('La restauración falló. Try again.');
    expect(monetizationNotice('statusUnavailable','fr-FR',MONETIZATION_NOTICE_LABELS_BY_LOCALE)).toBe('Subscription status unavailable · Restore purchases to refresh access');
    expect(paywallLabel('proIncludes','es',PAYWALL_LABELS_BY_LOCALE)).toContain('exportaciones ilimitadas');
    expect(recentScanAccessibilityLabel('Factura','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Abrir escaneo reciente Factura');
    expect(recentScanAccessibilityLabel('Invoice','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Ouvrir le scan récent Invoice');
    const spanishDocumentLabels = documentUiLabelsForLocale('es-MX', DOCUMENT_UI_LABELS_BY_LOCALE);
    expect(spanishDocumentLabels.reviewScan).toBe('Revisar escaneo');
    expect(spanishDocumentLabels.pagePlural).toBe('páginas');
    expect(spanishDocumentLabels.exportPreparing(2)).toBe('Preparando PDF de 2 páginas…');
    expect(documentUiLabelsForLocale('fr-FR', DOCUMENT_UI_LABELS_BY_LOCALE).reviewScan).toBe('Vérifier le scan');
    expect(documentUiLabelsForLocale('pt-BR', DOCUMENT_UI_LABELS_BY_LOCALE).reviewScan).toBe('Revisar digitalização');
    expect(documentUiLabelsForLocale('pt', DOCUMENT_UI_LABELS_BY_LOCALE).exportPreparing(1)).toBe('Preparando PDF de 1 página…');
    expect(documentUiLabelsForLocale('de-DE', DOCUMENT_UI_LABELS_BY_LOCALE).reviewScan).toBe('Review scan');
    expect(paywallProStartsAt('$4.99','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Pro comienza desde $4.99 al mes.');
    expect(paywallProductPrice('$49.99','year','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('$49.99 / año');
    expect(paywallCreditsRemaining(1,'es',PAYWALL_LABELS_BY_LOCALE)).toBe('Quedan 1 crédito de exportación');
    expect(pendingOfferAgeLabelForLocale(null,0,'es',PENDING_OFFER_AGE_LABELS_BY_LOCALE)).toBe('No hay ninguna compra pendiente');
    expect(paywallLabel('upgrade','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Actualizar a Pro');
    expect(paywallLabel('restorePurchases','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Restaurar compras');
    expect(paywallLabel('switchFreeMessage','es',PAYWALL_LABELS_BY_LOCALE)).toContain('facturación de producción');
    expect(paywallLabel('confirmFree','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Confirm switch to Free plan');
    expect(paywallPlanLabel('yourPlan','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Tu plan');
    expect(paywallPlanLabel('unlimitedExports','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Exportaciones ilimitadas');
    expect(paywallPlanLabel('ocrWatermarkFree','es',PAYWALL_LABELS_BY_LOCALE)).toBe('OCR y exportaciones sin marca de agua activados');
    expect(paywallPlanLabel('billingLocal','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Local billing provider');
    expect(biometricStatusLabel('available','Face ID','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Disponible: Face ID');
    expect(biometricStatusLabel('webFallback',undefined,'es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Respaldo web activado');
    expect(storageMigrationLabel('summary',1,2,4,5,1,0,'es',PAYWALL_LABELS_BY_LOCALE)).toContain('Migración de almacenamiento');
    expect(storageMigrationLabel('diagnostics',1,2,4,5,1,2,'fr-FR',PAYWALL_LABELS_BY_LOCALE)).toContain('Records retained: 4/5');
    expect(securityLabel('privacy','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Privacidad');
    expect(securityLabel('lockNow','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Bloquear ahora');
    expect(securityLabel('requireBiometrics','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Requerir datos biométricos');
    expect(securityLabel('localProcessing','es',PAYWALL_LABELS_BY_LOCALE)).toContain('procesan localmente');
    expect(securityTimeoutLabel(300000,'es',PAYWALL_LABELS_BY_LOCALE)).toBe('5 minutos');
    expect(securityTimeoutLabel(30000,'fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('30 seconds');
    expect(securityLabel('batchScanning','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Escaneo por lotes');
    expect(securityLabel('experimentalCrop','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Recorte experimental');
    expect(securityLabel('openBatchScan','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Open batch scan');
    expect(securityLabel('scannerFeatures','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Funciones del escáner');
    expect(securityLabel('ocrTextRecognition','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Reconocimiento de texto OCR');
    expect(securityLabel('documentProcessing','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Procesamiento de documentos');
    expect(securityLabel('scanQuality','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Scan quality');
    expect(securityLabel('advancedScanner','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Escáner avanzado');
    expect(securityLabel('lighting','es-MX',PAYWALL_LABELS_BY_LOCALE)).toBe('Iluminación');
    expect(securityLabel('goodQuality','es',PAYWALL_LABELS_BY_LOCALE)).toBe('Buena');
    expect(securityLabel('backToScan','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Retour au scan');
    expect(securityLabel('webDemoMode','es',PAYWALL_LABELS_BY_LOCALE)).toBe('MODO DEMO WEB');
    expect(securityLabel('cameraPreviewSimulated','es-MX',PAYWALL_LABELS_BY_LOCALE)).toContain('simulada');
    expect(securityLabel('openDocumentLibrary','fr-FR',PAYWALL_LABELS_BY_LOCALE)).toBe('Ouvrir la bibliothèque de documents');
    expect(securityLabel('pagePlural','es',PAYWALL_LABELS_BY_LOCALE)).toBe('páginas');
    expect(expiredRecoveryEventCount([{kind:'cancelled'},{kind:'completed'},{kind:'cancelled'}],false)).toBe(2);
    expect(expiredRecoveryEventCount([{kind:'cancelled'}],true)).toBe(0);
    expect(expiredRecoveryEventCount([{kind:'cancelled'},{kind:'completed'},{kind:'cancelled'}],true)).toBe(1);
    expect(restoreCancellationNotice(1,3)).toBe('1 restored, 2 remaining and recoverable.');
    expect(restoreCancellationAnnouncement(1,3)).toBe('Restore cancelled. 1 restored, 2 remaining and recoverable.');
    expect(restoreCancellationAnnouncementForLocale(1,3,'es',RECOVERY_ANNOUNCEMENT_LABELS_BY_LOCALE)).toBe('Restauración cancelada. 1 restaurado, 2 restantes y recuperables.');
    expect(restoreCancellationAnnouncementForLocale(2,2,'es-MX',RECOVERY_ANNOUNCEMENT_LABELS_BY_LOCALE)).toBe('Restauración cancelada. 2 restaurados, 0 restantes y recuperables.');
  });

  it('rejects empty or concurrent cleanup attempts',()=>{
    expect(canStartCleanup(false,2)).toBe(true);
    expect(canStartCleanup(false,0)).toBe(false);
    expect(canStartCleanup(true,2)).toBe(false);
  });
});
