import { asyncStorageAdapter, type StorageAdapter } from '../storage/StorageAdapter';

export const LANGUAGE_PREFERENCE_KEY = 'smart-document-scanner.language-preference';
export const SUPPORTED_APP_LANGUAGES = ['en', 'es', 'fr', 'pt'] as const;
export type AppLanguage = (typeof SUPPORTED_APP_LANGUAGES)[number];

export const APP_LANGUAGE_LABELS: Record<AppLanguage, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  pt: 'Português',
};

type LanguagePreferenceCopy = {
  title: string;
  description: string;
  usingCustom: string;
  usingDevice: string;
  reset: string;
  resetSuccess: string;
  resetFailure: string;
};

export const LANGUAGE_PREFERENCE_COPY_BY_LOCALE: Record<AppLanguage, LanguagePreferenceCopy> = {
  en: { title: 'Language', description: 'Choose the language used throughout the scanner.', usingCustom: 'Custom language selected', usingDevice: 'Following device language', reset: 'Use device language', resetSuccess: 'Language preference reset. The device language is now used.', resetFailure: 'Language preference could not be reset. Try again.' },
  es: { title: 'Idioma', description: 'Elige el idioma que se usará en el escáner.', usingCustom: 'Idioma personalizado seleccionado', usingDevice: 'Usando el idioma del dispositivo', reset: 'Usar idioma del dispositivo', resetSuccess: 'Preferencia de idioma restablecida. Ahora se usa el idioma del dispositivo.', resetFailure: 'No se pudo restablecer el idioma. Inténtalo de nuevo.' },
  fr: { title: 'Langue', description: 'Choisissez la langue utilisée dans le scanner.', usingCustom: 'Langue personnalisée sélectionnée', usingDevice: 'Langue de l’appareil utilisée', reset: 'Utiliser la langue de l’appareil', resetSuccess: 'Préférence de langue réinitialisée. La langue de l’appareil est maintenant utilisée.', resetFailure: 'Impossible de réinitialiser la langue. Réessayez.' },
  pt: { title: 'Idioma', description: 'Escolha o idioma usado no scanner.', usingCustom: 'Idioma personalizado selecionado', usingDevice: 'Usando o idioma do dispositivo', reset: 'Usar idioma do dispositivo', resetSuccess: 'Preferência de idioma redefinida. O idioma do dispositivo está sendo usado.', resetFailure: 'Não foi possível redefinir o idioma. Tente novamente.' },
};

export function languagePreferenceCopy(locale: string, registry = LANGUAGE_PREFERENCE_COPY_BY_LOCALE): LanguagePreferenceCopy {
  return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en;
}

type ActionCopy = { sharePdf: string; scanAnother: string; refreshRecovery: string; deleteDocument: string; cancel: string; save: string; rename: string; restore: string; close: string; previewUnavailable: string; editUnavailable: string; deleteTitle: string; deleteMessage: string; customPurchaseError: string; resetView: string; rotate: string; crop: string; enhance: string; filterPreview: string; saveFilter: string; adjustCrop: string; saveCrop: string; previousPage: string; nextPage: string; pageOf: (current: number, total: number) => string };
export const ACTION_COPY_BY_LOCALE: Record<AppLanguage, ActionCopy> = {
  en: { sharePdf: 'Share PDF', scanAnother: 'Scan another', refreshRecovery: 'Refresh recovery', deleteDocument: 'Delete document', cancel: 'Cancel', save: 'Save', rename: 'Rename', restore: 'Restore', close: 'Close', previewUnavailable: 'Preview unavailable', editUnavailable: 'Edit unavailable', deleteTitle: 'Delete document?', deleteMessage: 'This removes the scan from this device.', customPurchaseError: 'Purchase could not be completed.', resetView: 'Reset view', rotate: 'Rotate', crop: 'Crop', enhance: 'Enhance', filterPreview: 'Filter preview', saveFilter: 'Save filter', adjustCrop: 'Adjust crop handles', saveCrop: 'Save crop', previousPage: 'Previous', nextPage: 'Next', pageOf: (current,total) => `Page ${current} of ${total}` },
  es: { sharePdf: 'Compartir PDF', scanAnother: 'Escanear otro', refreshRecovery: 'Actualizar recuperación', deleteDocument: 'Eliminar documento', cancel: 'Cancelar', save: 'Guardar', rename: 'Cambiar nombre', restore: 'Restaurar', close: 'Cerrar', previewUnavailable: 'Vista previa no disponible', editUnavailable: 'Edición no disponible', deleteTitle: '¿Eliminar documento?', deleteMessage: 'El escaneo se eliminará de este dispositivo.', customPurchaseError: 'No se pudo completar la compra.', resetView: 'Restablecer vista', rotate: 'Rotar', crop: 'Recortar', enhance: 'Mejorar', filterPreview: 'Vista previa del filtro', saveFilter: 'Guardar filtro', adjustCrop: 'Ajustar recorte', saveCrop: 'Guardar recorte', previousPage: 'Anterior', nextPage: 'Siguiente', pageOf: (current,total) => `Página ${current} de ${total}` },
  fr: { sharePdf: 'Partager le PDF', scanAnother: 'Numériser un autre', refreshRecovery: 'Actualiser la récupération', deleteDocument: 'Supprimer le document', cancel: 'Annuler', save: 'Enregistrer', rename: 'Renommer', restore: 'Restaurer', close: 'Fermer', previewUnavailable: 'Aperçu indisponible', editUnavailable: 'Modification indisponible', deleteTitle: 'Supprimer le document ?', deleteMessage: 'Le scan sera supprimé de cet appareil.', customPurchaseError: 'Impossible de terminer l’achat.', resetView: 'Réinitialiser la vue', rotate: 'Pivoter', crop: 'Rogner', enhance: 'Améliorer', filterPreview: 'Aperçu du filtre', saveFilter: 'Enregistrer le filtre', adjustCrop: 'Ajuster le recadrage', saveCrop: 'Enregistrer le recadrage', previousPage: 'Précédente', nextPage: 'Suivante', pageOf: (current,total) => `Page ${current} sur ${total}` },
  pt: { sharePdf: 'Compartilhar PDF', scanAnother: 'Digitalizar outro', refreshRecovery: 'Atualizar recuperação', deleteDocument: 'Excluir documento', cancel: 'Cancelar', save: 'Salvar', rename: 'Renomear', restore: 'Restaurar', close: 'Fechar', previewUnavailable: 'Pré-visualização indisponível', editUnavailable: 'Edição indisponível', deleteTitle: 'Excluir documento?', deleteMessage: 'A digitalização será removida deste dispositivo.', customPurchaseError: 'Não foi possível concluir a compra.', resetView: 'Redefinir visualização', rotate: 'Girar', crop: 'Recortar', enhance: 'Melhorar', filterPreview: 'Pré-visualização do filtro', saveFilter: 'Salvar filtro', adjustCrop: 'Ajustar recorte', saveCrop: 'Salvar recorte', previousPage: 'Anterior', nextPage: 'Próxima', pageOf: (current,total) => `Página ${current} de ${total}` },
};
export function actionCopy(locale: string, registry = ACTION_COPY_BY_LOCALE): ActionCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type BatchCopy = { disabled: string; noReadablePhotos: string; readyToProcess: (count: number) => string; chooseFailed: (detail: string) => string; permissionFallback: string; selectBeforeProcess: string; complete: string; attention: string; processFailed: (detail: string) => string; processFallback: string; noFailedPages: string; processBeforeExport: string; exported: string; exportFailed: (detail: string) => string; exportFallback: string; page: (n: number) => string; needsAttention: string; processed: string; waiting: string; error: string; ready: string; queued: string; startTitle: string; startDescription: string; title: string; subtitle: string; pages: (count: number) => string; choosePages: string; chooseDescription: string; choosePhotos: string; selected: (count: number) => string; progress: (done: number, total: number) => string; process: string; retry: string; export: (count: number) => string; queue: string; reviewReady: string; noPages: string; back: string; emptyTitle: string; emptyDescription: string };
export const BATCH_COPY_BY_LOCALE: Record<AppLanguage, BatchCopy> = {
  en: { disabled: 'Batch scanning is disabled in Settings.', noReadablePhotos: 'No readable photos were selected.', permissionFallback: 'Please check photo permissions and try again.', readyToProcess: count => `${count} page${count === 1 ? '' : 's'} ready to process.`, chooseFailed: detail => `Could not choose photos. ${detail}`, selectBeforeProcess: 'Select at least one photo before processing.', complete: 'Batch scan complete.', attention: 'Some pages need attention.', processFailed: detail => `Batch processing failed. ${detail}`, processFallback: 'Try processing the photos again.', noFailedPages: 'There are no failed pages to retry.', processBeforeExport: 'Process at least one page before exporting.', exported: 'Batch exported to Documents.', exportFailed: detail => `Unable to export the processed pages. ${detail}`, exportFallback: 'Try exporting again after processing the remaining pages.', page: n => `Page ${n}`, needsAttention: 'Processing needs attention', processed: 'Processed successfully', waiting: 'Waiting to process', error: 'Error', ready: 'Ready', queued: 'Queued', startTitle: 'Start with a few pages', startDescription: 'Batch scan is ideal for receipts, forms, or a stack of notes.', title: 'Batch scan', subtitle: 'Process multiple pages together, then export one clean PDF.', pages: count => `${count} page${count === 1 ? '' : 's'}`, choosePages: 'Choose your pages', chooseDescription: 'Select several photos from your library.', choosePhotos: 'Choose photos', selected: count => `${count} selected`, progress: (done,total) => `Processing ${done} of ${total}`, process: 'Process batch', retry: 'Retry failed', export: count => `Export ${count || ''} successful`, queue: 'Page queue', reviewReady: 'Ready for review', noPages: 'No pages yet', back: 'Back to Settings', emptyTitle: 'Start with a few pages', emptyDescription: 'Batch scan is ideal for receipts, forms, or a stack of notes.' },
  es: { disabled: 'El escaneo por lotes está desactivado en Ajustes.', noReadablePhotos: 'No se seleccionaron fotos legibles.', permissionFallback: 'Comprueba los permisos de fotos e inténtalo de nuevo.', readyToProcess: count => `${count} página${count === 1 ? '' : 's'} lista${count === 1 ? '' : 's'} para procesar.`, chooseFailed: detail => `No se pudieron elegir las fotos. ${detail}`, selectBeforeProcess: 'Selecciona al menos una foto antes de procesar.', complete: 'Escaneo por lotes completado.', attention: 'Algunas páginas requieren atención.', processFailed: detail => `Falló el procesamiento por lotes. ${detail}`, processFallback: 'Intenta procesar las fotos de nuevo.', noFailedPages: 'No hay páginas fallidas para reintentar.', processBeforeExport: 'Procesa al menos una página antes de exportar.', exported: 'Lote exportado a Documentos.', exportFailed: detail => `No se pudieron exportar las páginas procesadas. ${detail}`, exportFallback: 'Intenta exportar de nuevo después de procesar las páginas restantes.', page: n => `Página ${n}`, needsAttention: 'El procesamiento requiere atención', processed: 'Procesada correctamente', waiting: 'Esperando procesamiento', error: 'Error', ready: 'Lista', queued: 'En cola', startTitle: 'Empieza con unas páginas', startDescription: 'El escaneo por lotes es ideal para recibos, formularios o notas.', title: 'Escaneo por lotes', subtitle: 'Procesa varias páginas juntas y exporta un PDF limpio.', pages: count => `${count} página${count === 1 ? '' : 's'}`, choosePages: 'Elige tus páginas', chooseDescription: 'Selecciona varias fotos de tu biblioteca.', choosePhotos: 'Elegir fotos', selected: count => `${count} seleccionadas`, progress: (done,total) => `Procesando ${done} de ${total}`, process: 'Procesar lote', retry: 'Reintentar fallidas', export: count => `Exportar ${count || ''} procesadas`, queue: 'Cola de páginas', reviewReady: 'Lista para revisar', noPages: 'Aún no hay páginas', back: 'Volver a Ajustes', emptyTitle: 'Empieza con unas páginas', emptyDescription: 'El escaneo por lotes es ideal para recibos, formularios o notas.' },
  fr: { disabled: 'La numérisation par lots est désactivée dans Réglages.', noReadablePhotos: 'Aucune photo lisible n’a été sélectionnée.', permissionFallback: 'Vérifiez les autorisations des photos et réessayez.', readyToProcess: count => `${count} page${count === 1 ? '' : 's'} prête${count === 1 ? '' : 's'} à traiter.`, chooseFailed: detail => `Impossible de choisir les photos. ${detail}`, selectBeforeProcess: 'Sélectionnez au moins une photo avant le traitement.', complete: 'Numérisation par lots terminée.', attention: 'Certaines pages nécessitent votre attention.', processFailed: detail => `Échec du traitement par lots. ${detail}`, processFallback: 'Réessayez de traiter les photos.', noFailedPages: 'Aucune page en échec à réessayer.', processBeforeExport: 'Traitez au moins une page avant l’exportation.', exported: 'Lot exporté dans Documents.', exportFailed: detail => `Impossible d’exporter les pages traitées. ${detail}`, exportFallback: 'Réessayez l’exportation après avoir traité les pages restantes.', page: n => `Page ${n}`, needsAttention: 'Le traitement nécessite votre attention', processed: 'Traitée avec succès', waiting: 'En attente de traitement', error: 'Erreur', ready: 'Prête', queued: 'En file', startTitle: 'Commencez avec quelques pages', startDescription: 'La numérisation par lots convient aux reçus, formulaires et notes.', title: 'Numérisation par lots', subtitle: 'Traitez plusieurs pages ensemble, puis exportez un PDF propre.', pages: count => `${count} page${count === 1 ? '' : 's'}`, choosePages: 'Choisir vos pages', chooseDescription: 'Sélectionnez plusieurs photos dans votre bibliothèque.', choosePhotos: 'Choisir des photos', selected: count => `${count} sélectionnée${count === 1 ? '' : 's'}`, progress: (done,total) => `Traitement de ${done} sur ${total}`, process: 'Traiter le lot', retry: 'Réessayer les échecs', export: count => `Exporter ${count || ''} réussie${count === 1 ? '' : 's'}`, queue: 'File de pages', reviewReady: 'Prête à vérifier', noPages: 'Aucune page pour le moment', back: 'Retour aux réglages', emptyTitle: 'Commencez avec quelques pages', emptyDescription: 'La numérisation par lots convient aux reçus, formulaires et notes.' },
  pt: { disabled: 'A digitalização em lote está desativada em Configurações.', noReadablePhotos: 'Nenhuma foto legível foi selecionada.', permissionFallback: 'Verifique as permissões das fotos e tente novamente.', readyToProcess: count => `${count} página${count === 1 ? '' : 's'} pronta${count === 1 ? '' : 's'} para processar.`, chooseFailed: detail => `Não foi possível escolher as fotos. ${detail}`, selectBeforeProcess: 'Selecione pelo menos uma foto antes de processar.', complete: 'Digitalização em lote concluída.', attention: 'Algumas páginas precisam de atenção.', processFailed: detail => `Falha ao processar o lote. ${detail}`, processFallback: 'Tente processar as fotos novamente.', noFailedPages: 'Não há páginas com falha para tentar novamente.', processBeforeExport: 'Processe pelo menos uma página antes de exportar.', exported: 'Lote exportado para Documentos.', exportFailed: detail => `Não foi possível exportar as páginas processadas. ${detail}`, exportFallback: 'Tente exportar novamente após processar as páginas restantes.', page: n => `Página ${n}`, needsAttention: 'O processamento precisa de atenção', processed: 'Processada com sucesso', waiting: 'Aguardando processamento', error: 'Erro', ready: 'Pronta', queued: 'Na fila', startTitle: 'Comece com algumas páginas', startDescription: 'A digitalização em lote é ideal para recibos, formulários ou notas.', title: 'Digitalização em lote', subtitle: 'Processe várias páginas juntas e exporte um PDF limpo.', pages: count => `${count} página${count === 1 ? '' : 's'}`, choosePages: 'Escolha suas páginas', chooseDescription: 'Selecione várias fotos da sua biblioteca.', choosePhotos: 'Escolher fotos', selected: count => `${count} selecionadas`, progress: (done,total) => `Processando ${done} de ${total}`, process: 'Processar lote', retry: 'Tentar novamente', export: count => `Exportar ${count || ''} processadas`, queue: 'Fila de páginas', reviewReady: 'Pronta para revisão', noPages: 'Nenhuma página ainda', back: 'Voltar para Configurações', emptyTitle: 'Comece com algumas páginas', emptyDescription: 'A digitalização em lote é ideal para recibos, formulários ou notas.' },
};
export function batchCopy(locale: string, registry = BATCH_COPY_BY_LOCALE): BatchCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type PaywallErrorCopy = { restoreStateFailed: (detail: string) => string; pendingCheckFailed: (detail: string) => string; purchaseFailed: (detail: string) => string; selectionSaveFailed: (detail: string) => string; storeRefreshFailed: (detail: string) => string; alreadyActive: string; unlocked: string; restored: string; restoring: string; retryGuidance: string };
export const PAYWALL_ERROR_COPY_BY_LOCALE: Record<AppLanguage, PaywallErrorCopy> = {
  en: { restoreStateFailed: detail => `Unable to restore paywall state. ${detail}`, pendingCheckFailed: detail => `Pending purchase check failed. ${detail}`, purchaseFailed: detail => `Purchase could not be completed. ${detail}`, selectionSaveFailed: detail => `Could not save your selection. ${detail}`, storeRefreshFailed: detail => `Store status could not be refreshed. ${detail}`, alreadyActive: 'This offer is already active.', unlocked: 'Pro unlocked.', restored: 'Pro access restored.', restoring: 'Refreshing store status…', retryGuidance: 'If this continues, verify the store account and contact support with the diagnostics summary.' },
  es: { restoreStateFailed: detail => `No se pudo restaurar el estado de la pantalla de compra. ${detail}`, pendingCheckFailed: detail => `Falló la comprobación de la compra pendiente. ${detail}`, purchaseFailed: detail => `No se pudo completar la compra. ${detail}`, selectionSaveFailed: detail => `No se pudo guardar tu selección. ${detail}`, storeRefreshFailed: detail => `No se pudo actualizar el estado de la tienda. ${detail}`, alreadyActive: 'Esta oferta ya está activa.', unlocked: 'Pro desbloqueado.', restored: 'Acceso Pro restaurado.', restoring: 'Actualizando el estado de la tienda…', retryGuidance: 'Si el problema continúa, verifica la cuenta de la tienda y contacta con soporte usando el resumen de diagnóstico.' },
  fr: { restoreStateFailed: detail => `Impossible de restaurer l’état de l’achat. ${detail}`, pendingCheckFailed: detail => `Échec de la vérification de l’achat en attente. ${detail}`, purchaseFailed: detail => `Impossible de terminer l’achat. ${detail}`, selectionSaveFailed: detail => `Impossible d’enregistrer votre sélection. ${detail}`, storeRefreshFailed: detail => `Impossible d’actualiser l’état de la boutique. ${detail}`, alreadyActive: 'Cette offre est déjà active.', unlocked: 'Pro est activé.', restored: 'Accès Pro restauré.', restoring: 'Actualisation de l’état de la boutique…', retryGuidance: 'Si le problème persiste, vérifiez le compte de la boutique et contactez l’assistance avec le résumé des diagnostics.' },
  pt: { restoreStateFailed: detail => `Não foi possível restaurar o estado da compra. ${detail}`, pendingCheckFailed: detail => `Falha ao verificar a compra pendente. ${detail}`, purchaseFailed: detail => `Não foi possível concluir a compra. ${detail}`, selectionSaveFailed: detail => `Não foi possível salvar sua seleção. ${detail}`, storeRefreshFailed: detail => `Não foi possível atualizar o estado da loja. ${detail}`, alreadyActive: 'Esta oferta já está ativa.', unlocked: 'Pro desbloqueado.', restored: 'Acesso Pro restaurado.', restoring: 'Atualizando o estado da loja…', retryGuidance: 'Se o problema continuar, verifique a conta da loja e entre em contato com o suporte usando o resumo dos diagnósticos.' },
};
export function paywallErrorCopy(locale: string, registry = PAYWALL_ERROR_COPY_BY_LOCALE): PaywallErrorCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type PaywallSurfaceCopy = { eyebrow: string; defaultTitle: string; defaultSubtitle: string; ocrTitle: string; ocrSubtitle: string; creditsTitle: string; creditsSubtitle: string; selectYearly: string; yearlyPro: string; monthlyPro: string; lifetimePro: string; selected: string; choose: string; selection: string; confirm: string; confirmPurchase: string; continueWith: (plan: string) => string; cancel: string; pendingPurchase: (id: string) => string; retryPurchase: string; pendingRecoveryEscalation: string; pendingRecoverySupport: string; restorePurchases: string; refreshStore: string; notNow: string; selectYearlyA11y: string };
export const PAYWALL_SURFACE_COPY_BY_LOCALE: Record<AppLanguage, PaywallSurfaceCopy> = {
  en: { eyebrow: 'SCANNER PRO', defaultTitle: 'Everything you need to finish documents faster.', defaultSubtitle: 'Unlock unlimited exports, OCR, cloud backup, watermark-free PDFs, and priority support.', ocrTitle: 'Turn scans into searchable text.', ocrSubtitle: 'Unlock OCR to find words inside your documents and search your library faster.', creditsTitle: 'Keep exporting without interruptions.', creditsSubtitle: 'Pro removes export-credit limits and keeps your document workflow moving.', selectYearly: 'Select yearly', yearlyPro: 'Yearly Pro', monthlyPro: 'Monthly Pro', lifetimePro: 'Lifetime Pro', selected: 'Selected', choose: 'Choose', selection: 'Your selection', confirm: 'Confirm', confirmPurchase: 'Confirm purchase', continueWith: plan => `Continue with ${plan} Pro`, cancel: 'Cancel', pendingPurchase: id => `Pending purchase: ${id}. Restore purchases to check store access.`, retryPurchase: 'Retry purchase', pendingRecoveryEscalation: 'Automatic retry limit reached. Restore purchases or contact support to finish checking your Pro access.', pendingRecoverySupport: 'Open diagnostics', restorePurchases: 'Restore purchases', refreshStore: 'Refresh store status', notNow: 'Not now', selectYearlyA11y: 'Select yearly Pro plan' },
  es: { eyebrow: 'SCANNER PRO', defaultTitle: 'Todo lo que necesitas para terminar documentos más rápido.', defaultSubtitle: 'Desbloquea exportaciones ilimitadas, OCR, copia de seguridad en la nube, PDF sin marca de agua y soporte prioritario.', ocrTitle: 'Convierte tus escaneos en texto que puedas buscar.', ocrSubtitle: 'Desbloquea OCR para encontrar palabras dentro de tus documentos y buscar más rápido.', creditsTitle: 'Sigue exportando sin interrupciones.', creditsSubtitle: 'Pro elimina los límites de créditos de exportación y mantiene tu flujo de documentos en marcha.', selectYearly: 'Elegir anual', yearlyPro: 'Pro anual', monthlyPro: 'Pro mensual', lifetimePro: 'Pro de por vida', selected: 'Seleccionado', choose: 'Elegir', selection: 'Tu selección', confirm: 'Confirmar', confirmPurchase: 'Confirmar compra', continueWith: plan => `Continuar con Pro ${plan}`, cancel: 'Cancelar', pendingPurchase: id => `Compra pendiente: ${id}. Restaura las compras para comprobar el acceso a la tienda.`, retryPurchase: 'Reintentar compra', pendingRecoveryEscalation: 'Se alcanzó el límite de reintentos automáticos. Restaura las compras o contacta con soporte para comprobar el acceso Pro.', pendingRecoverySupport: 'Abrir diagnósticos', restorePurchases: 'Restaurar compras', refreshStore: 'Actualizar estado de la tienda', notNow: 'Ahora no', selectYearlyA11y: 'Elegir plan Pro anual' },
  fr: { eyebrow: 'SCANNER PRO', defaultTitle: 'Tout ce qu’il vous faut pour terminer vos documents plus vite.', defaultSubtitle: 'Débloquez les exportations illimitées, l’OCR, la sauvegarde cloud, les PDF sans filigrane et l’assistance prioritaire.', ocrTitle: 'Transformez vos scans en texte consultable.', ocrSubtitle: 'Débloquez l’OCR pour trouver des mots dans vos documents et effectuer des recherches plus rapidement.', creditsTitle: 'Continuez à exporter sans interruption.', creditsSubtitle: 'Pro supprime les limites de crédits d’exportation et fluidifie votre travail documentaire.', selectYearly: 'Choisir l’offre annuelle', yearlyPro: 'Pro annuel', monthlyPro: 'Pro mensuel', lifetimePro: 'Pro à vie', selected: 'Sélectionné', choose: 'Choisir', selection: 'Votre sélection', confirm: 'Confirmer', confirmPurchase: 'Confirmer l’achat', continueWith: plan => `Continuer avec Pro ${plan}`, cancel: 'Annuler', pendingPurchase: id => `Achat en attente : ${id}. Restaurez les achats pour vérifier l’accès à la boutique.`, retryPurchase: 'Réessayer l’achat', pendingRecoveryEscalation: 'La limite de tentatives automatiques est atteinte. Restaurez les achats ou contactez l’assistance pour vérifier votre accès Pro.', pendingRecoverySupport: 'Ouvrir les diagnostics', restorePurchases: 'Restaurer les achats', refreshStore: 'Actualiser l’état de la boutique', notNow: 'Pas maintenant', selectYearlyA11y: 'Choisir l’offre Pro annuelle' },
  pt: { eyebrow: 'SCANNER PRO', defaultTitle: 'Tudo o que você precisa para terminar documentos mais rápido.', defaultSubtitle: 'Desbloqueie exportações ilimitadas, OCR, backup na nuvem, PDFs sem marca d’água e suporte prioritário.', ocrTitle: 'Transforme digitalizações em texto pesquisável.', ocrSubtitle: 'Desbloqueie o OCR para encontrar palavras nos documentos e pesquisar sua biblioteca mais rapidamente.', creditsTitle: 'Continue exportando sem interrupções.', creditsSubtitle: 'O Pro remove os limites de créditos de exportação e mantém seu fluxo de documentos em andamento.', selectYearly: 'Escolher anual', yearlyPro: 'Pro anual', monthlyPro: 'Pro mensal', lifetimePro: 'Pro vitalício', selected: 'Selecionado', choose: 'Escolher', selection: 'Sua seleção', confirm: 'Confirmar', confirmPurchase: 'Confirmar compra', continueWith: plan => `Continuar com Pro ${plan}`, cancel: 'Cancelar', pendingPurchase: id => `Compra pendente: ${id}. Restaure as compras para verificar o acesso à loja.`, retryPurchase: 'Tentar compra novamente', pendingRecoveryEscalation: 'O limite de tentativas automáticas foi atingido. Restaure as compras ou contate o suporte para verificar seu acesso Pro.', pendingRecoverySupport: 'Abrir diagnósticos', restorePurchases: 'Restaurar compras', refreshStore: 'Atualizar estado da loja', notNow: 'Agora não', selectYearlyA11y: 'Escolher plano Pro anual' },
};
export function paywallSurfaceCopy(locale: string, registry = PAYWALL_SURFACE_COPY_BY_LOCALE): PaywallSurfaceCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type ReviewFallbackCopy = { noReadableImage: string; cameraNoImage: string; exportPaused: string; storageFull: (label: string) => string; noPdf: string; exportFailed: string; retryExport: string; copySuccess: string; copyFailed: string; copyFallback: string };
export const REVIEW_FALLBACK_COPY_BY_LOCALE: Record<AppLanguage, ReviewFallbackCopy> = {
  en: { noReadableImage: 'No readable image was selected. Choose another photo and try again.', cameraNoImage: 'The camera returned no readable image. Please try again.', exportPaused: 'Export paused until local storage is cleaned up.', storageFull: label => `Local storage is nearly full (${label}). Remove an older document before exporting this PDF.`, noPdf: 'No PDF was produced.', exportFailed: 'Unable to create the PDF. Check the pages and try exporting again.', retryExport: 'Retry export', copySuccess: 'Sanitized diagnostics copied.', copyFailed: 'Could not copy diagnostics.', copyFallback: 'You can still read the summary here.' },
  es: { noReadableImage: 'No se seleccionó una imagen legible. Elige otra foto e inténtalo de nuevo.', cameraNoImage: 'La cámara no devolvió una imagen legible. Inténtalo de nuevo.', exportPaused: 'La exportación está pausada hasta liberar espacio local.', storageFull: label => `El almacenamiento local está casi lleno (${label}). Elimina un documento anterior antes de exportar este PDF.`, noPdf: 'No se produjo ningún PDF.', exportFailed: 'No se pudo crear el PDF. Comprueba las páginas e inténtalo de nuevo.', retryExport: 'Reintentar exportación', copySuccess: 'Diagnósticos sanitizados copiados.', copyFailed: 'No se pudieron copiar los diagnósticos.', copyFallback: 'Todavía puedes leer el resumen aquí.' },
  fr: { noReadableImage: 'Aucune image lisible n’a été sélectionnée. Choisissez une autre photo et réessayez.', cameraNoImage: 'La caméra n’a renvoyé aucune image lisible. Réessayez.', exportPaused: 'L’exportation est en pause jusqu’à la libération d’espace local.', storageFull: label => `Le stockage local est presque plein (${label}). Supprimez un ancien document avant d’exporter ce PDF.`, noPdf: 'Aucun PDF n’a été produit.', exportFailed: 'Impossible de créer le PDF. Vérifiez les pages et réessayez.', retryExport: 'Réessayer l’exportation', copySuccess: 'Diagnostics nettoyés copiés.', copyFailed: 'Impossible de copier les diagnostics.', copyFallback: 'Vous pouvez toujours lire le résumé ici.' },
  pt: { noReadableImage: 'Nenhuma imagem legível foi selecionada. Escolha outra foto e tente novamente.', cameraNoImage: 'A câmera não retornou uma imagem legível. Tente novamente.', exportPaused: 'A exportação foi pausada até liberar espaço local.', storageFull: label => `O armazenamento local está quase cheio (${label}). Remova um documento antigo antes de exportar este PDF.`, noPdf: 'Nenhum PDF foi produzido.', exportFailed: 'Não foi possível criar o PDF. Verifique as páginas e tente exportar novamente.', retryExport: 'Tentar exportar novamente', copySuccess: 'Diagnósticos sanitizados copiados.', copyFailed: 'Não foi possível copiar os diagnósticos.', copyFallback: 'Você ainda pode ler o resumo aqui.' },
};
export function reviewFallbackCopy(locale: string, registry = REVIEW_FALLBACK_COPY_BY_LOCALE): ReviewFallbackCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type SettingsDiagnosticCopy = { checkingSubscription: string; diagnosticsUnavailable: string; subscriptionUnavailable: string; restoreAccess: string; restoreSettingsFailed: (detail: string) => string; savePreferenceFailed: (detail: string) => string; saveSucceeded: string; saveLockFailed: (detail: string) => string; retrySave: string };
export const SETTINGS_DIAGNOSTIC_COPY_BY_LOCALE: Record<AppLanguage, SettingsDiagnosticCopy> = {
  en: { checkingSubscription: 'Checking subscription status…', diagnosticsUnavailable: 'Subscription diagnostics unavailable', subscriptionUnavailable: 'Subscription status unavailable', restoreAccess: 'Restore purchases to refresh access', restoreSettingsFailed: detail => `Unable to restore Settings. ${detail}`, savePreferenceFailed: detail => `Could not save this preference. ${detail}`, saveSucceeded: 'Settings saved.', saveLockFailed: detail => `Could not save lock preferences. ${detail}`, retrySave: 'Retry save' },
  es: { checkingSubscription: 'Comprobando el estado de la suscripción…', diagnosticsUnavailable: 'Diagnósticos de suscripción no disponibles', subscriptionUnavailable: 'Estado de suscripción no disponible', restoreAccess: 'Restaura las compras para actualizar el acceso', restoreSettingsFailed: detail => `No se pudo restaurar Ajustes. ${detail}`, savePreferenceFailed: detail => `No se pudo guardar esta preferencia. ${detail}`, saveSucceeded: 'Ajustes guardados.', saveLockFailed: detail => `No se pudieron guardar las preferencias de bloqueo. ${detail}`, retrySave: 'Reintentar guardado' },
  fr: { checkingSubscription: 'Vérification de l’état de l’abonnement…', diagnosticsUnavailable: 'Diagnostics d’abonnement indisponibles', subscriptionUnavailable: 'État de l’abonnement indisponible', restoreAccess: 'Restaurez les achats pour actualiser l’accès', restoreSettingsFailed: detail => `Impossible de restaurer les réglages. ${detail}`, savePreferenceFailed: detail => `Impossible d’enregistrer cette préférence. ${detail}`, saveSucceeded: 'Réglages enregistrés.', saveLockFailed: detail => `Impossible d’enregistrer les réglages de verrouillage. ${detail}`, retrySave: 'Réessayer l’enregistrement' },
  pt: { checkingSubscription: 'Verificando o status da assinatura…', diagnosticsUnavailable: 'Diagnósticos da assinatura indisponíveis', subscriptionUnavailable: 'Status da assinatura indisponível', restoreAccess: 'Restaure as compras para atualizar o acesso', restoreSettingsFailed: detail => `Não foi possível restaurar as Configurações. ${detail}`, savePreferenceFailed: detail => `Não foi possível salvar esta preferência. ${detail}`, saveSucceeded: 'Configurações salvas.', saveLockFailed: detail => `Não foi possível salvar as preferências de bloqueio. ${detail}`, retrySave: 'Tentar salvar novamente' },
};
export function settingsDiagnosticCopy(locale: string, registry = SETTINGS_DIAGNOSTIC_COPY_BY_LOCALE): SettingsDiagnosticCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type SubscriptionDiagnosticInput = { tier: 'free' | 'monthly' | 'yearly' | 'lifetime'; provider: 'local' | 'production'; cache: 'fresh' | 'stale' | 'missing'; lastAction: 'none' | 'purchase' | 'restore' | 'refresh' };
type SubscriptionDiagnosticCopy = { title: string; tier: Record<SubscriptionDiagnosticInput['tier'], string>; provider: Record<SubscriptionDiagnosticInput['provider'], string>; cache: Record<SubscriptionDiagnosticInput['cache'], string>; lastAction: Record<SubscriptionDiagnosticInput['lastAction'], string> };
const SUBSCRIPTION_DIAGNOSTIC_COPY_BY_LOCALE: Record<AppLanguage, SubscriptionDiagnosticCopy> = {
  en: { title: 'Subscription diagnostics', tier: { free: 'Free', monthly: 'Pro monthly', yearly: 'Pro yearly', lifetime: 'Pro lifetime' }, provider: { local: 'Local billing', production: 'Store billing' }, cache: { fresh: 'Fresh', stale: 'Stale', missing: 'Missing' }, lastAction: { none: 'None', purchase: 'Purchase', restore: 'Restore', refresh: 'Refresh' } },
  es: { title: 'Diagnósticos de suscripción', tier: { free: 'Gratis', monthly: 'Pro mensual', yearly: 'Pro anual', lifetime: 'Pro vitalicio' }, provider: { local: 'Facturación local', production: 'Facturación de la tienda' }, cache: { fresh: 'Actual', stale: 'Antigua', missing: 'No disponible' }, lastAction: { none: 'Ninguna', purchase: 'Compra', restore: 'Restauración', refresh: 'Actualización' } },
  fr: { title: 'Diagnostics d’abonnement', tier: { free: 'Gratuit', monthly: 'Pro mensuel', yearly: 'Pro annuel', lifetime: 'Pro à vie' }, provider: { local: 'Facturation locale', production: 'Facturation de la boutique' }, cache: { fresh: 'À jour', stale: 'Obsolète', missing: 'Manquant' }, lastAction: { none: 'Aucune', purchase: 'Achat', restore: 'Restauration', refresh: 'Actualisation' } },
  pt: { title: 'Diagnósticos da assinatura', tier: { free: 'Grátis', monthly: 'Pro mensal', yearly: 'Pro anual', lifetime: 'Pro vitalício' }, provider: { local: 'Cobrança local', production: 'Cobrança da loja' }, cache: { fresh: 'Atual', stale: 'Desatualizado', missing: 'Ausente' }, lastAction: { none: 'Nenhuma', purchase: 'Compra', restore: 'Restauração', refresh: 'Atualização' } },
};
export function localizedSubscriptionDiagnostics(input: SubscriptionDiagnosticInput, locale: string): string {
  const copy = SUBSCRIPTION_DIAGNOSTIC_COPY_BY_LOCALE[normalizeAppLanguage(locale) ?? 'en'] ?? SUBSCRIPTION_DIAGNOSTIC_COPY_BY_LOCALE.en;
  return `${copy.title}: ${copy.tier[input.tier]} · ${copy.provider[input.provider]} · ${copy.cache[input.cache]} · ${copy.lastAction[input.lastAction]}`;
}

type ExternalLinkCopy = { open: string; failureTitle: string; failureMessage: string };
export const EXTERNAL_LINK_COPY_BY_LOCALE: Record<AppLanguage, ExternalLinkCopy> = {
  en: { open: 'Open link', failureTitle: 'Unable to open link', failureMessage: 'Please check your connection and try again.' },
  es: { open: 'Abrir enlace', failureTitle: 'No se pudo abrir el enlace', failureMessage: 'Comprueba tu conexión e inténtalo de nuevo.' },
  fr: { open: 'Ouvrir le lien', failureTitle: 'Impossible d’ouvrir le lien', failureMessage: 'Vérifiez votre connexion et réessayez.' },
  pt: { open: 'Abrir link', failureTitle: 'Não foi possível abrir o link', failureMessage: 'Verifique sua conexão e tente novamente.' },
};
export function externalLinkCopy(locale: string, registry = EXTERNAL_LINK_COPY_BY_LOCALE): ExternalLinkCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type RecoveryStatusCopy = { label: string; title: string; unavailable: string; savedLessHour: string; savedHours: (hours: number) => string; savedDays: (days: number) => string; stale: string; restore: string; delete: string; refresh: string };
export const RECOVERY_STATUS_COPY_BY_LOCALE: Record<AppLanguage, RecoveryStatusCopy> = {
  en: { label: 'Local recovery status', title: 'Local recovery', unavailable: 'No recovery copy is available yet.', savedLessHour: 'Saved less than an hour ago', savedHours: hours => `Saved ${hours} hour${hours === 1 ? '' : 's'} ago`, savedDays: days => `Saved ${days} day${days === 1 ? '' : 's'} ago`, stale: 'This backup is more than a week old. Scan or edit a document to refresh it.', restore: 'Restore', delete: 'Delete', refresh: 'Refresh' },
  es: { label: 'Estado de recuperación local', title: 'Recuperación local', unavailable: 'Todavía no hay una copia de recuperación disponible.', savedLessHour: 'Guardado hace menos de una hora', savedHours: hours => `Guardado hace ${hours} hora${hours === 1 ? '' : 's'}`, savedDays: days => `Guardado hace ${days} día${days === 1 ? '' : 's'}`, stale: 'Esta copia tiene más de una semana. Escanea o edita un documento para actualizarla.', restore: 'Restaurar', delete: 'Eliminar', refresh: 'Actualizar' },
  fr: { label: 'État de la récupération locale', title: 'Récupération locale', unavailable: 'Aucune copie de récupération n’est disponible pour le moment.', savedLessHour: 'Enregistré il y a moins d’une heure', savedHours: hours => `Enregistré il y a ${hours} heure${hours === 1 ? '' : 's'}`, savedDays: days => `Enregistré il y a ${days} jour${days === 1 ? '' : 's'}`, stale: 'Cette sauvegarde date de plus d’une semaine. Scannez ou modifiez un document pour l’actualiser.', restore: 'Restaurer', delete: 'Supprimer', refresh: 'Actualiser' },
  pt: { label: 'Status da recuperação local', title: 'Recuperação local', unavailable: 'Ainda não há uma cópia de recuperação disponível.', savedLessHour: 'Salvo há menos de uma hora', savedHours: hours => `Salvo há ${hours} hora${hours === 1 ? '' : 's'}`, savedDays: days => `Salvo há ${days} dia${days === 1 ? '' : 's'}`, stale: 'Este backup tem mais de uma semana. Digitalize ou edite um documento para atualizá-lo.', restore: 'Restaurar', delete: 'Excluir', refresh: 'Atualizar' },
};
export function recoveryStatusCopy(locale: string, registry = RECOVERY_STATUS_COPY_BY_LOCALE): RecoveryStatusCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }
export function recoveryBackupAgeLabel(savedAt: number | null, now: number, locale: string): string { const copy = recoveryStatusCopy(locale); if (!savedAt) return copy.unavailable; const age = Math.max(0, now - savedAt); if (age < 60 * 60 * 1000) return copy.savedLessHour; const days = Math.floor(age / (24 * 60 * 60 * 1000)); if (days > 0) return copy.savedDays(days); return copy.savedHours(Math.floor(age / (60 * 60 * 1000))); }
export function recoveryLastSavedLabel(savedAt: number, locale: string): string { const language = normalizeAppLanguage(locale) ?? 'en'; const prefix = language === 'es' ? 'Último guardado' : language === 'fr' ? 'Dernier enregistrement' : language === 'pt' ? 'Último salvamento' : 'Last saved'; return `${prefix}: ${new Intl.DateTimeFormat(language, { dateStyle: 'medium', timeStyle: 'short' }).format(savedAt)}`; }

type ReviewFeedbackCopy = { dismiss: string; cancelled: string; failed: string; preparing: string; available: string; processed: (completed: number, total: number) => string; cancel: string; retry: string; diagnostics: string; close: string; copyDiagnostics: string };
export const REVIEW_FEEDBACK_COPY_BY_LOCALE: Record<AppLanguage, ReviewFeedbackCopy> = {
  en: { dismiss: 'Dismiss', cancelled: 'Export cancelled', failed: 'Export needs attention', preparing: 'Preparing PDF', available: 'Your pages are still available. You can retry when ready.', processed: (completed, total) => `${completed} of ${total} pages processed`, cancel: 'Cancel export', retry: 'Retry export', diagnostics: 'Troubleshooting details', close: 'Close', copyDiagnostics: 'Copy sanitized diagnostics' },
  es: { dismiss: 'Cerrar', cancelled: 'Exportación cancelada', failed: 'La exportación requiere atención', preparing: 'Preparando PDF', available: 'Tus páginas siguen disponibles. Puedes volver a intentarlo cuando quieras.', processed: (completed, total) => `${completed} de ${total} páginas procesadas`, cancel: 'Cancelar exportación', retry: 'Reintentar exportación', diagnostics: 'Detalles de solución de problemas', close: 'Cerrar', copyDiagnostics: 'Copiar diagnósticos sanitizados' },
  fr: { dismiss: 'Fermer', cancelled: 'Exportation annulée', failed: 'L’exportation nécessite votre attention', preparing: 'Préparation du PDF', available: 'Vos pages sont toujours disponibles. Vous pourrez réessayer quand vous serez prêt.', processed: (completed, total) => `${completed} page${completed === 1 ? '' : 's'} sur ${total} traitée${completed === 1 ? '' : 's'}`, cancel: 'Annuler l’exportation', retry: 'Réessayer l’exportation', diagnostics: 'Détails de dépannage', close: 'Fermer', copyDiagnostics: 'Copier les diagnostics nettoyés' },
  pt: { dismiss: 'Fechar', cancelled: 'Exportação cancelada', failed: 'A exportação requer atenção', preparing: 'Preparando PDF', available: 'Suas páginas continuam disponíveis. Você pode tentar novamente quando estiver pronto.', processed: (completed, total) => `${completed} de ${total} páginas processadas`, cancel: 'Cancelar exportação', retry: 'Tentar exportação novamente', diagnostics: 'Detalhes para solução de problemas', close: 'Fechar', copyDiagnostics: 'Copiar diagnósticos sanitizados' },
};
export function reviewFeedbackCopy(locale: string, registry = REVIEW_FEEDBACK_COPY_BY_LOCALE): ReviewFeedbackCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type PreviewCopy = { noDocument: string; startScan: string; ready: string; share: string; newScan: string; page: (count: number) => string };
export const PREVIEW_COPY_BY_LOCALE: Record<AppLanguage, PreviewCopy> = {
  en: { noDocument: 'No active document', startScan: 'Start a scan', ready: 'PDF ready to share', share: 'Share PDF', newScan: 'New scan', page: count => `${count} page${count === 1 ? '' : 's'}` },
  es: { noDocument: 'No hay ningún documento activo', startScan: 'Iniciar un escaneo', ready: 'PDF listo para compartir', share: 'Compartir PDF', newScan: 'Nuevo escaneo', page: count => `${count} página${count === 1 ? '' : 's'}` },
  fr: { noDocument: 'Aucun document actif', startScan: 'Démarrer un scan', ready: 'PDF prêt à être partagé', share: 'Partager le PDF', newScan: 'Nouveau scan', page: count => `${count} page${count === 1 ? '' : 's'}` },
  pt: { noDocument: 'Nenhum documento ativo', startScan: 'Iniciar digitalização', ready: 'PDF pronto para compartilhar', share: 'Compartilhar PDF', newScan: 'Nova digitalização', page: count => `${count} página${count === 1 ? '' : 's'}` },
};
export function previewCopy(locale: string, registry = PREVIEW_COPY_BY_LOCALE): PreviewCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type ErrorBoundaryCopy = { eyebrow: string; title: string; screenFailed: string; retry: string; hint: string };
export const ERROR_BOUNDARY_COPY_BY_LOCALE: Record<AppLanguage, ErrorBoundaryCopy> = {
  en: { eyebrow: 'SMART DOCUMENT SCANNER', title: 'Something went wrong', screenFailed: 'The screen could not be displayed.', retry: 'Try again', hint: 'Your local documents are still stored on this device.' },
  es: { eyebrow: 'SMART DOCUMENT SCANNER', title: 'Algo salió mal', screenFailed: 'No se pudo mostrar la pantalla.', retry: 'Intentar de nuevo', hint: 'Tus documentos locales siguen guardados en este dispositivo.' },
  fr: { eyebrow: 'SMART DOCUMENT SCANNER', title: 'Une erreur est survenue', screenFailed: 'L’écran n’a pas pu être affiché.', retry: 'Réessayer', hint: 'Vos documents locaux sont toujours enregistrés sur cet appareil.' },
  pt: { eyebrow: 'SMART DOCUMENT SCANNER', title: 'Algo deu errado', screenFailed: 'Não foi possível exibir a tela.', retry: 'Tentar novamente', hint: 'Seus documentos locais continuam armazenados neste dispositivo.' },
};
export function errorBoundaryCopy(locale: string, registry = ERROR_BOUNDARY_COPY_BY_LOCALE): ErrorBoundaryCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type LockCopy = { title: string; prompt: string; unlock: string; fallback: string; authIncomplete: string; unlockFailed: (detail: string) => string; settingsFailed: (detail: string) => string; locked: string; expired: string; manual: string; saveFailed: (detail: string) => string };
export const LOCK_COPY_BY_LOCALE: Record<AppLanguage, LockCopy> = {
  en: { title: 'Documents locked', prompt: 'Use Face ID or your device fingerprint to continue.', unlock: 'Unlock', fallback: 'Biometric lock uses a safe fallback in this environment.', authIncomplete: 'Authentication was not completed. Try again to unlock your documents.', unlockFailed: detail => `Unlock failed. ${detail}`, settingsFailed: detail => `Security settings could not be loaded. ${detail}`, locked: 'The app was locked. Unlock to continue.', expired: 'Your session expired. Unlock to continue.', manual: 'The app was locked manually. Unlock to continue.', saveFailed: detail => `The app was locked, but security state could not be saved. ${detail}` },
  es: { title: 'Documentos bloqueados', prompt: 'Usa Face ID o la huella del dispositivo para continuar.', unlock: 'Desbloquear', fallback: 'El bloqueo biométrico usa una alternativa segura en este entorno.', authIncomplete: 'La autenticación no se completó. Inténtalo de nuevo para desbloquear tus documentos.', unlockFailed: detail => `No se pudo desbloquear. ${detail}`, settingsFailed: detail => `No se pudieron cargar los ajustes de seguridad. ${detail}`, locked: 'La aplicación está bloqueada. Desbloquéala para continuar.', expired: 'Tu sesión expiró. Desbloquéala para continuar.', manual: 'La aplicación se bloqueó manualmente. Desbloquéala para continuar.', saveFailed: detail => `La aplicación se bloqueó, pero no se pudo guardar el estado de seguridad. ${detail}` },
  fr: { title: 'Documents verrouillés', prompt: 'Utilisez Face ID ou l’empreinte de votre appareil pour continuer.', unlock: 'Déverrouiller', fallback: 'Le verrouillage biométrique utilise une solution de secours sûre dans cet environnement.', authIncomplete: 'L’authentification n’est pas terminée. Réessayez pour déverrouiller vos documents.', unlockFailed: detail => `Échec du déverrouillage. ${detail}`, settingsFailed: detail => `Les réglages de sécurité n’ont pas pu être chargés. ${detail}`, locked: 'L’application est verrouillée. Déverrouillez-la pour continuer.', expired: 'Votre session a expiré. Déverrouillez-la pour continuer.', manual: 'L’application a été verrouillée manuellement. Déverrouillez-la pour continuer.', saveFailed: detail => `L’application a été verrouillée, mais l’état de sécurité n’a pas pu être enregistré. ${detail}` },
  pt: { title: 'Documentos bloqueados', prompt: 'Use o Face ID ou a impressão digital do dispositivo para continuar.', unlock: 'Desbloquear', fallback: 'O bloqueio biométrico usa uma alternativa segura neste ambiente.', authIncomplete: 'A autenticação não foi concluída. Tente novamente para desbloquear seus documentos.', unlockFailed: detail => `Falha ao desbloquear. ${detail}`, settingsFailed: detail => `Não foi possível carregar as configurações de segurança. ${detail}`, locked: 'O aplicativo está bloqueado. Desbloqueie para continuar.', expired: 'Sua sessão expirou. Desbloqueie para continuar.', manual: 'O aplicativo foi bloqueado manualmente. Desbloqueie para continuar.', saveFailed: detail => `O aplicativo foi bloqueado, mas não foi possível salvar o estado de segurança. ${detail}` },
};
export function lockCopy(locale: string, registry = LOCK_COPY_BY_LOCALE): LockCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type InspectorCopy = { guidance: string; previewError: string; editError: string; filterError: string; cropError: string };
export const INSPECTOR_COPY_BY_LOCALE: Record<AppLanguage, InspectorCopy> = {
  en: { guidance: 'Pinch or double-tap to zoom · Swipe to change pages', previewError: 'Preview unavailable', editError: 'The page could not be updated. Your original scan is still safe.', filterError: 'This filter could not be saved. Your original page is still safe.', cropError: 'The crop could not be saved. Your current page is still safe.' },
  es: { guidance: 'Pellizca o toca dos veces para ampliar · Desliza para cambiar de página', previewError: 'Vista previa no disponible', editError: 'No se pudo actualizar la página. El escaneo original sigue protegido.', filterError: 'No se pudo guardar este filtro. La página original sigue protegida.', cropError: 'No se pudo guardar el recorte. La página actual sigue protegida.' },
  fr: { guidance: 'Pincez ou touchez deux fois pour zoomer · Balayez pour changer de page', previewError: 'Aperçu indisponible', editError: 'La page n’a pas pu être mise à jour. Votre scan original est conservé.', filterError: 'Impossible d’enregistrer ce filtre. Votre page originale est conservée.', cropError: 'Impossible d’enregistrer le recadrage. Votre page actuelle est conservée.' },
  pt: { guidance: 'Aperte ou toque duas vezes para ampliar · Deslize para mudar de página', previewError: 'Pré-visualização indisponível', editError: 'Não foi possível atualizar a página. O scan original está seguro.', filterError: 'Não foi possível salvar este filtro. A página original está segura.', cropError: 'Não foi possível salvar o recorte. A página atual está segura.' },
};
export function inspectorCopy(locale: string, registry = INSPECTOR_COPY_BY_LOCALE): InspectorCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type HistoryCopy = { title: string; text: string; revertLatest: string; restoring: string; latest: string; restoreUnavailableTitle: string; restoreUnavailableMessage: string; restoreSavedTitle: string; restoreSavedMessage: string; backToDocuments: string; lastUpdated: string; storedLocally: string; favorite: string; save: string };
export const HISTORY_COPY_BY_LOCALE: Record<AppLanguage, HistoryCopy> = {
  en: { title: 'Edit history', text: 'Up to 3 recent versions are kept locally for quick recovery.', revertLatest: 'Revert latest', restoring: 'Restoring…', latest: 'Latest', restoreUnavailableTitle: 'Revert unavailable', restoreUnavailableMessage: 'The selected version could not be restored. Your current document is unchanged.', restoreSavedTitle: 'Restore saved version?', restoreSavedMessage: 'Newer history entries will be removed.', backToDocuments: 'Back to Documents', lastUpdated: 'LAST UPDATED', storedLocally: 'Stored locally', favorite: 'Favorite', save: 'Save' },
  es: { title: 'Historial de ediciones', text: 'Las 3 versiones más recientes se guardan localmente para recuperarlas rápidamente.', revertLatest: 'Revertir última', restoring: 'Restaurando…', latest: 'Más reciente', restoreUnavailableTitle: 'No se puede revertir', restoreUnavailableMessage: 'No se pudo restaurar la versión seleccionada. El documento actual no ha cambiado.', restoreSavedTitle: '¿Restaurar versión guardada?', restoreSavedMessage: 'Se eliminarán las entradas más recientes del historial.', backToDocuments: 'Volver a documentos', lastUpdated: 'ÚLTIMA ACTUALIZACIÓN', storedLocally: 'Guardado localmente', favorite: 'Favorito', save: 'Guardar' },
  fr: { title: 'Historique des modifications', text: 'Jusqu’à 3 versions récentes sont conservées localement pour une récupération rapide.', revertLatest: 'Rétablir la dernière', restoring: 'Restauration…', latest: 'Dernière', restoreUnavailableTitle: 'Rétablissement indisponible', restoreUnavailableMessage: 'La version sélectionnée n’a pas pu être restaurée. Votre document actuel est inchangé.', restoreSavedTitle: 'Restaurer la version enregistrée ?', restoreSavedMessage: 'Les entrées plus récentes de l’historique seront supprimées.', backToDocuments: 'Retour aux documents', lastUpdated: 'DERNIÈRE MISE À JOUR', storedLocally: 'Stocké localement', favorite: 'Favori', save: 'Enregistrer' },
  pt: { title: 'Histórico de edições', text: 'Até 3 versões recentes são mantidas localmente para recuperação rápida.', revertLatest: 'Reverter última', restoring: 'Restaurando…', latest: 'Mais recente', restoreUnavailableTitle: 'Não foi possível reverter', restoreUnavailableMessage: 'A versão selecionada não pôde ser restaurada. O documento atual não foi alterado.', restoreSavedTitle: 'Restaurar versão salva?', restoreSavedMessage: 'As entradas mais recentes do histórico serão removidas.', backToDocuments: 'Voltar aos documentos', lastUpdated: 'ÚLTIMA ATUALIZAÇÃO', storedLocally: 'Armazenado localmente', favorite: 'Favorito', save: 'Salvar' },
};
export function historyCopy(locale: string, registry = HISTORY_COPY_BY_LOCALE): HistoryCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type DocumentMetaCopy = { titleInput: string; saveTitle: string; renameTitle: string; pages: string; total: string; inspectPage: (n: number) => string; previewPage: (n: number) => string; pageLabel: (n: number) => string; originalCapture: string; filterName: (name: string) => string; danger: string; deleteLocalWarning: string };
export const DOCUMENT_META_COPY_BY_LOCALE: Record<AppLanguage, DocumentMetaCopy> = {
  en: { titleInput: 'Document title', saveTitle: 'Save document title', renameTitle: 'Rename document', pages: 'Pages', total: 'total', inspectPage: n => `Inspect page ${n}`, previewPage: n => `Preview of page ${n}`, pageLabel: n => `Page ${n}`, originalCapture: 'Original capture', filterName: name => `${name} filter`, danger: 'DANGER ZONE', deleteLocalWarning: 'Deleting removes this document from local storage.' },
  es: { titleInput: 'Título del documento', saveTitle: 'Guardar título del documento', renameTitle: 'Cambiar nombre del documento', pages: 'Páginas', total: 'en total', inspectPage: n => `Inspeccionar página ${n}`, previewPage: n => `Vista previa de la página ${n}`, pageLabel: n => `Página ${n}`, originalCapture: 'Captura original', filterName: name => `Filtro ${name}`, danger: 'ZONA DE PELIGRO', deleteLocalWarning: 'El documento se eliminará del almacenamiento local.' },
  fr: { titleInput: 'Titre du document', saveTitle: 'Enregistrer le titre du document', renameTitle: 'Renommer le document', pages: 'Pages', total: 'au total', inspectPage: n => `Inspecter la page ${n}`, previewPage: n => `Aperçu de la page ${n}`, pageLabel: n => `Page ${n}`, originalCapture: 'Capture originale', filterName: name => `Filtre ${name}`, danger: 'ZONE DANGEREUSE', deleteLocalWarning: 'La suppression retire ce document du stockage local.' },
  pt: { titleInput: 'Título do documento', saveTitle: 'Salvar título do documento', renameTitle: 'Renomear documento', pages: 'Páginas', total: 'no total', inspectPage: n => `Inspecionar página ${n}`, previewPage: n => `Pré-visualização da página ${n}`, pageLabel: n => `Página ${n}`, originalCapture: 'Captura original', filterName: name => `Filtro ${name}`, danger: 'ZONA DE PERIGO', deleteLocalWarning: 'A exclusão remove este documento do armazenamento local.' },
};
export function documentMetaCopy(locale: string, registry = DOCUMENT_META_COPY_BY_LOCALE): DocumentMetaCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type DocumentPresentationCopy = { eyebrow: string; readyTitle: string; readyMessage: (pages: number) => string };
export const DOCUMENT_PRESENTATION_COPY_BY_LOCALE: Record<AppLanguage, DocumentPresentationCopy> = {
  en: { eyebrow: 'DOCUMENT DETAILS', readyTitle: 'Your document is ready', readyMessage: pages => `PDF saved locally with ${pages} ${pages === 1 ? 'page' : 'pages'}. What would you like to do next?` },
  es: { eyebrow: 'DETALLES DEL DOCUMENTO', readyTitle: 'Tu documento está listo', readyMessage: pages => `PDF guardado localmente con ${pages} ${pages === 1 ? 'página' : 'páginas'}. ¿Qué quieres hacer ahora?` },
  fr: { eyebrow: 'DÉTAILS DU DOCUMENT', readyTitle: 'Votre document est prêt', readyMessage: pages => `PDF enregistré localement avec ${pages} ${pages === 1 ? 'page' : 'pages'}. Que souhaitez-vous faire ensuite ?` },
  pt: { eyebrow: 'DETALHES DO DOCUMENTO', readyTitle: 'Seu documento está pronto', readyMessage: pages => `PDF salvo localmente com ${pages} ${pages === 1 ? 'página' : 'páginas'}. O que você deseja fazer agora?` },
};
export function documentPresentationCopy(locale: string, registry = DOCUMENT_PRESENTATION_COPY_BY_LOCALE): DocumentPresentationCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

type DocumentNoticeCopy = { recoveryRefreshed: string; recoveryFailed: (detail: string) => string; noticeDetail: (detail: string) => string; renamed: string; editSaved: string; pdfShared: string; renameFailed: (detail: string) => string; editFailed: (detail: string) => string; pdfShareFailed: (detail: string) => string; deleteFailed: (detail: string) => string; restoreFailed: (detail: string) => string; galleryDeleted: (title: string) => string; galleryRestored: (title: string) => string; galleryRefreshFailed: (detail: string) => string; searchIndexFailed: (detail: string) => string; favoriteUpdated: (title: string, favorite: boolean) => string; favoriteFailed: (detail: string) => string; suggestionsFailed: (detail: string) => string };
export const DOCUMENT_NOTICE_COPY_BY_LOCALE: Record<AppLanguage, DocumentNoticeCopy> = {
  en: { recoveryRefreshed: 'Recovery copy refreshed.', recoveryFailed: detail => `Recovery refresh failed. ${detail}`, noticeDetail: detail => detail, renamed: 'Document title updated.', editSaved: 'Edit saved safely.', pdfShared: 'PDF shared successfully.', renameFailed: detail => `Document title could not be updated. ${detail}`, editFailed: detail => `Edit could not be saved. ${detail}`, pdfShareFailed: detail => `PDF could not be shared. ${detail}`, deleteFailed: detail => `Document could not be deleted. ${detail}`, restoreFailed: detail => `Saved version could not be restored. ${detail}`, galleryDeleted: title => `${title} was deleted.`, galleryRestored: title => `${title} was restored.`, galleryRefreshFailed: detail => `Documents could not be refreshed. ${detail}`, searchIndexFailed: detail => `Search index unavailable. ${detail}`, favoriteUpdated: (title, favorite) => `${title} ${favorite ? 'added to' : 'removed from'} favorites.`, favoriteFailed: detail => `Favorite could not be updated. ${detail}`, suggestionsFailed: detail => `Search suggestions unavailable. ${detail}` },
  es: { recoveryRefreshed: 'Copia de recuperación actualizada.', recoveryFailed: detail => `Falló la actualización de recuperación. ${detail}`, noticeDetail: detail => detail, renamed: 'Título del documento actualizado.', editSaved: 'Edición guardada de forma segura.', pdfShared: 'PDF compartido correctamente.', renameFailed: detail => `No se pudo actualizar el título del documento. ${detail}`, editFailed: detail => `No se pudo guardar la edición. ${detail}`, pdfShareFailed: detail => `No se pudo compartir el PDF. ${detail}`, deleteFailed: detail => `No se pudo eliminar el documento. ${detail}`, restoreFailed: detail => `No se pudo restaurar la versión guardada. ${detail}`, galleryDeleted: title => `${title} se eliminó.`, galleryRestored: title => `${title} se restauró.`, galleryRefreshFailed: detail => `No se pudieron actualizar los documentos. ${detail}`, searchIndexFailed: detail => `El índice de búsqueda no está disponible. ${detail}`, favoriteUpdated: (title, favorite) => `${title} ${favorite ? 'se añadió a' : 'se quitó de'} favoritos.`, favoriteFailed: detail => `No se pudo actualizar el favorito. ${detail}`, suggestionsFailed: detail => `Las sugerencias de búsqueda no están disponibles. ${detail}` },
  fr: { recoveryRefreshed: 'Copie de récupération actualisée.', recoveryFailed: detail => `Échec de l’actualisation de la récupération. ${detail}`, noticeDetail: detail => detail, renamed: 'Titre du document mis à jour.', editSaved: 'Modification enregistrée en toute sécurité.', pdfShared: 'PDF partagé avec succès.', renameFailed: detail => `Le titre du document n’a pas pu être mis à jour. ${detail}`, editFailed: detail => `La modification n’a pas pu être enregistrée. ${detail}`, pdfShareFailed: detail => `Le PDF n’a pas pu être partagé. ${detail}`, deleteFailed: detail => `Le document n’a pas pu être supprimé. ${detail}`, restoreFailed: detail => `La version enregistrée n’a pas pu être restaurée. ${detail}`, galleryDeleted: title => `${title} a été supprimé.`, galleryRestored: title => `${title} a été restauré.`, galleryRefreshFailed: detail => `Les documents n’ont pas pu être actualisés. ${detail}`, searchIndexFailed: detail => `L’index de recherche n’est pas disponible. ${detail}`, favoriteUpdated: (title, favorite) => `${title} ${favorite ? 'a été ajouté aux' : 'a été retiré des'} favoris.`, favoriteFailed: detail => `Le favori n’a pas pu être mis à jour. ${detail}`, suggestionsFailed: detail => `Les suggestions de recherche ne sont pas disponibles. ${detail}` },
  pt: { recoveryRefreshed: 'Cópia de recuperação atualizada.', recoveryFailed: detail => `Falha ao atualizar a recuperação. ${detail}`, noticeDetail: detail => detail, renamed: 'Título do documento atualizado.', editSaved: 'Edição salva com segurança.', pdfShared: 'PDF compartilhado com sucesso.', renameFailed: detail => `Não foi possível atualizar o título do documento. ${detail}`, editFailed: detail => `Não foi possível salvar a edição. ${detail}`, pdfShareFailed: detail => `Não foi possível compartilhar o PDF. ${detail}`, deleteFailed: detail => `Não foi possível excluir o documento. ${detail}`, restoreFailed: detail => `Não foi possível restaurar a versão salva. ${detail}`, galleryDeleted: title => `${title} foi excluído.`, galleryRestored: title => `${title} foi restaurado.`, galleryRefreshFailed: detail => `Não foi possível atualizar os documentos. ${detail}`, searchIndexFailed: detail => `O índice de pesquisa não está disponível. ${detail}`, favoriteUpdated: (title, favorite) => `${title} ${favorite ? 'foi adicionado aos' : 'foi removido dos'} favoritos.`, favoriteFailed: detail => `Não foi possível atualizar o favorito. ${detail}`, suggestionsFailed: detail => `As sugestões de pesquisa não estão disponíveis. ${detail}` },
};
export function documentNoticeCopy(locale: string, registry = DOCUMENT_NOTICE_COPY_BY_LOCALE): DocumentNoticeCopy { return registry[normalizeAppLanguage(locale) ?? 'en'] ?? registry.en; }

const FILTER_NAMES_BY_LOCALE: Record<AppLanguage, Record<string, string>> = {
  en: { original: 'Original', enhanced: 'Enhanced', grayscale: 'Grayscale', blackAndWhite: 'Black and white' },
  es: { original: 'Original', enhanced: 'Mejorado', grayscale: 'Escala de grises', blackAndWhite: 'Blanco y negro' },
  fr: { original: 'Original', enhanced: 'Amélioré', grayscale: 'Niveaux de gris', blackAndWhite: 'Noir et blanc' },
  pt: { original: 'Original', enhanced: 'Melhorado', grayscale: 'Escala de cinza', blackAndWhite: 'Preto e branco' },
};
export function localizedFilterName(name: string, locale: string): string { return FILTER_NAMES_BY_LOCALE[normalizeAppLanguage(locale) ?? 'en'][name] ?? name; }

export function normalizeAppLanguage(value: string | null | undefined): AppLanguage | null {
  const normalized = value?.trim().toLowerCase().split('-')[0];
  return SUPPORTED_APP_LANGUAGES.includes(normalized as AppLanguage) ? normalized as AppLanguage : null;
}

export function resolveAppLocale(preference: AppLanguage | null | undefined, deviceLocale?: string): string {
  if (preference) return preference;
  const deviceLanguage = normalizeAppLanguage(deviceLocale);
  return deviceLanguage ?? 'en';
}

export async function loadLanguagePreference(storage: StorageAdapter = asyncStorageAdapter): Promise<AppLanguage | null> {
  try {
    return normalizeAppLanguage(await storage.get(LANGUAGE_PREFERENCE_KEY));
  } catch {
    return null;
  }
}

export async function saveLanguagePreference(language: AppLanguage, storage: StorageAdapter = asyncStorageAdapter): Promise<void> {
  await storage.set(LANGUAGE_PREFERENCE_KEY, language);
}

export async function clearLanguagePreference(storage: StorageAdapter = asyncStorageAdapter): Promise<void> {
  await storage.remove(LANGUAGE_PREFERENCE_KEY);
}
